### ISSUE TITLE
`README.md` needs to be split up per connector

### ISSUE THREAD

**Issue by tjtelan** [infinyon/kafka-connector#29]
In the website reference update automation, we use the README included as part of each connector package.

https://github.com/infinyon/fluvio-website/blob/master/scripts/fluvio-cms/src/connectors/cli.rs#L107-L109

For Kafka, we build 2 separate packages (1 per data direction). However, the same README.md is included with both connectors. This ends up needing to be fixed manually, which is not the workflow we want.

**Comment by sehz** [comment]
Yes, we should separate out README.
